name: Build and deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install
        run: |
          npm ci
          npm install -g @sonar/scan

      - name: Build
        run: npm run build

      - name: Token check
        run: |
            if [ -z "$SONAR_TOKEN" ]; then
              echo "❌ SONAR_TOKEN is EMPTY"
              exit 1
            else
              echo "✅ SONAR_TOKEN is set"
            fi
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Scan
        run: npx sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.GITHUB_TOKEN }}
