name: Build and deploy to GitHub Pages && AWS && GCP

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install
        run: |
          npm ci
          npm install -g @sonar/scan

      - name: Build
        run: npm run build
        env:
          PUBLIC_URL: .

      - name: SonarQube Scan
        run: npx sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # =========================
      # GitHub Pages deploy
      # =========================
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.GITHUB_TOKEN }}

      # =========================
      # AWS CONFIG
      # =========================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3 bucket
        run: |
          aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Deploy to AWS Amplify
        run: |
          cd build
          zip -r ../build.zip .
          cd ..

          DEPLOYMENT=$(aws amplify create-deployment \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --branch-name staging)

          UPLOAD_URL=$(echo $DEPLOYMENT | jq -r '.zipUploadUrl')
          JOB_ID=$(echo $DEPLOYMENT | jq -r '.jobId')

          curl -X PUT --upload-file build.zip "$UPLOAD_URL"

          aws amplify start-deployment \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --branch-name staging \
            --job-id $JOB_ID

      # =========================
      # GCP CONFIG
      # =========================
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup GCP SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Sync to GCS bucket
        run: |
          gsutil -m rsync -r -d build gs://${{ secrets.GCS_BUCKET_NAME }}
